### ISSUE TITLE
Replace JZlib by JRE Deflater/Inflater

### ISSUE THREAD

**Issue by hongospongo** [mwiede/jsch#114]
Version 0.1.65 integrated JZlib to allow the usage of zlib@openssh.com & zlib compressions.
I suggest including the code from http://www.jcraft.com/jsch/examples/CompressionJUZ.java instead, which wraps the native java.util.zip.Deflater/Inflater classes. This reduces library size and greatly improves compression performance.

NB: we have been using the above wrapper for many years without any problems.

**Comment by norrisjeremy** [comment]
So I have a couple concerns with fully removing the JZlib implementation and replacing it with this alternative:

1. This JUZ implementation isn't technically compliant with [RFC 4253 6.2](https://datatracker.ietf.org/doc/html/rfc4253#section-6.2), in that it performs Z_SYNC_FLUSH operations instead of Z_PARTIAL_FLUSH operations. In practice, this probably doesn't matter for interoperability purposes, since any usable Zlib implementation used by remote server for decompression should handle either operation. I've looked at a few other SSH implementations: [OpenSSH](https://github.com/openssh/openssh-portable/blob/master/packet.c#L758) & [libssh2](https://github.com/libssh2/libssh2/blob/master/src/comp.c#L200) both utilize Z_PARTIAL_FLUSH, while [Dropbear](https://github.com/mkj/dropbear/blob/master/packet.c#L756) & [Mina SSHD](https://github.com/apache/mina-sshd/blob/master/sshd-common/src/main/java/org/apache/sshd/common/compression/CompressionZlib.java#L67) both utilize Z_SYNC_FLUSH.
2. This JUZ implementation doesn't contain any sort of copyright/license attribution. IANAL, so I'm uncertain how problematic this would be if we incorporated it into this fork.

We could possibly include it in this fork along side the JZlib implementation, since a user could opt into using it manually, although the unclear copyright/license for the code might be problematic with regards to directly distributing it.
@mwiede What are your thoughts?

**Comment by norrisjeremy** [comment]
FYI, here is the original [JSch-users thread on Sourceforge](https://sourceforge.net/p/jsch/mailman/jsch-users/thread/201202031343.WAA19979%40jcraft.com/#msg28781313) from whence this JUZ implementation appears to have originated.

**Comment by norrisjeremy** [comment]
Also, here is a page that describes the differences between [Z_PARTIAL_FLUSH & Z_SYNC_FLUSH](https://www.bolet.org/~pornin/deflate-flush.html).

**Comment by hongospongo** [comment]
To be honest, I was not aware of these subtle diffeneces in the zlib implementations. In my naive imagination I considered the JUZ code to be fully compatible,

So the only thing I can contribute still at this point is to say that we are using the JUZ wrapper in a reallife project where we exchange large amout of data with about 100 different SFTP servers and that we never had any problems so far.
