### ISSUE TITLE
JSch for DBeaver

### ISSUE THREAD

**Issue by nimda7** [mwiede/jsch#214]
There's a popular DB management tool - DBeaver. And it has the old JSch version, which doesn't work with ed25519 keys. 
This tool is built around the Eclipse platform.
Is it possible to install your version instead of packaged one? It uses "Software sites" to install\update.

**Comment by mwiede** [comment]
I found several issues, which talk about the same issue. Replacing Jsch would have to be done at easiest at build time of the software, so the developers should do it and not the end user.

In order to get ed25519 keys working I guess the quickest is that you switch to sshj like in https://github.com/dbeaver/dbeaver/issues/15783#issuecomment-1063323475

**Comment by nimda7** [comment]
Unfortunately, SSHJ is broken even more than JSCH.
Since Eclipse-based software uses "plugins" for additional functionality instead of building a whole software by developers. 
My question was about how to possibly replace this plugin, which is shipped as a JAR file. 
Possibly there's a way to build a single jar for plugin-like usage. Sorry for that explanation, I have not much idea how this java software works internally.
