### ISSUE TITLE
为什么不内置尽可能多的密钥协商算法

### ISSUE THREAD

**Issue by w-sf** [mwiede/jsch#380]
我在陆续接入一些设备，总是需要不断修改
JSch.setConfig("xxx",JSch.getConfig("xxx")+",more")
这不是一个好办法，因为其他都可以正常工作
并且"是否安全"应该是服务端需要考虑的问题，客户端本来就应该尽可能的保证连接成功

**Comment by deskangel** [comment]
Yeah, I'm confused about this too. 
[#234](https://github.com/mwiede/jsch/issues/234#issuecomment-1331616665)

**Comment by norrisjeremy** [comment]
Hi @w-sf & @deskangel,

We strive to have JSch only utilize secure crypto algorithms by default, since this a client library for the SSH (_**Secure**_ Shell) Protocol.
If you want to utilize older, weaker, _**insecure**_ crypto algorithms, then you will need to positively consent by manually enabling their use via one of the several methods we provide.
If you disagree with this policy, you are free to create and publish your own JSch fork, reversing this decision.

Thanks,
Jeremy
