### ISSUE TITLE
Connection negotiation fails when sFTP-server does not provide a "PubkeyAcceptedAlgorithms" preference list

### ISSUE THREAD

**Issue by HubertOT** [mwiede/jsch#412]
Hi,

During communication with an sFTP-server the error "`com.jcraft.jsch.JSchException: Auth fail for methods 'publickey'`" is thrown after upgrade from jsch 0.1.55 to 0.2.11.

Further investigation shows the concerning sFTP-server does not provide a preference list for "PucKeyAcceptedAlgorithms" (server_host_key):

> DEBUG: PubkeyAcceptedAlgorithms = ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
DEBUG: No server-sig-algs found, using PubkeyAcceptedAlgorithms = [ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-dss]

The server seems to abort the connection setup after first algorithm negotiation failure.
Setting on client site the "PubkeyAcceptedAlgorithms" to only "ssh-rsa" the connection is successful.

As we don't have influence on the remote sFTP-server, I have two questions:

1. is the  "PubkeyAcceptedAlgorithms" (server_host_key) list mandatory for a sFTP-server?
2. If no preference list is provided by the sFTP-server, what should the default behavior (algorithm) be (of the client)?

**Comment by norrisjeremy** [comment]
Hi @HubertOT,

The log messages you provided above indicate that the server to which you are connecting doesn't support the `server-sig-algs` extension from [RFC 8332](https://datatracker.ietf.org/doc/html/rfc8332).
This is not a setting that the client and server negotiate like other crypto algorithms, but rather simply is used as a hint supplied by the server for the client (JSch in this case) as to which signature algorithms that the server finds acceptable for public key authentication.
If the server supports this extension, JSch simply uses it to filter the algorithms specified in the PubkeyAcceptedAlgorithms setting you provide to only try to use algorithms the server explicitly hints that it supports.
For older servers that do not support it (such as the server you are using), then the behavior falls back to using the PubkeyAcceptedAlgorithms without any filtering like it did in the past.

What type of SSH key are you using that succeeds with the older 0.1.55 release that fails for you with the current 0.2.11 release?
If it is an RSA type key, perhaps the server to which you are connecting doesn't handle RSA/SHA2 very well (rsa-sha2-512/rsa-sha2-256) and thus fails.
If that is the case, you could try adjusting PubkeyAcceptedAlgorithms to not include those two algorithms so that JSch will only try with the older (insecure) RSA/SHA1 signature algorithm (ssh-rsa).

Thanks,
Jeremy

**Comment by HubertOT** [comment]
Hi @norrisjeremy, Thank you for your clear answer. Based on https://datatracker.ietf.org/doc/html/[draft-ietf-curdle-ssh-ext-info-09](https://datatracker.ietf.org/doc/html/draft-ietf-curdle-ssh-ext-info-09) this was not clear to me. Also not if the list was mandatory or not (MUST versus SHOULD used over there).
Indeed RSA is used, so I will try your suggestion leaving the rsa-sha2-512 and rsa-sha2-256 out of the accepted public key algorithms list.
Could it also help to e.g. put within the list ssh-rsa before rsa-sha2-512 and rsa-sha2-256 within the list or is the order not used?

If you have an answer on my last question that would be great. Otherwise this issue can be closed as answered.

**Comment by norrisjeremy** [comment]
Hi @HubertOT,

Yes, if the problem you are having is indeed related to the rsa-sha2-512 & rsa-sha2-256 algorithms, then you could also simply ensure that ssh-rsa appears earlier in the list than those algorithms, assuming the server you are connecting to doesn't support the server-sig-algs extension.

Thanks,
Jeremy

**Comment by HubertOT** [comment]
Thank you, tested it already and it works.
