### ISSUE TITLE
Can it support SM2 SM4？

### ISSUE THREAD

**Issue by jokerskai** [mwiede/jsch#576]
Can it support SM2 SM4？

**Comment by mwiede** [comment]
At the moment it is not. After I googled I only found a note on https://www.thunes.com/news/digital-signature-usage-of-chinese-cryptography-standards/     regarding an implementation in Java at all.

**Comment by mwiede** [comment]
https://github.com/Tencent/TencentKonaSMSuite

**Comment by jokerskai** [comment]
China is currently switching to SM encryption algorithm, and the file transfer tool that supports SM encryption algorithm has not been found. I hope JSCH can support SM encryption algorithm.OpenEuler Operating system SM3 SM4 SM2-SM3.  you can test interoperability on it.Thanks.

**Comment by mwiede** [comment]
I think it is possible to integrate the tencent suite, but somebody has to do it, this is open source

**Comment by norrisjeremy** [comment]
> I think it is possible to integrate the tencent suite, but somebody has to do it, this is open source

Unless someone can point to some other functioning SSH server that implements these algorithms, I'm not sure why JSch would integrate them, as there would be no point to them since they wouldn't offer any practical interoperability.

I would also encourage users for which this is important to work with the recently formed [SSHM](https://datatracker.ietf.org/wg/sshm/about/) working group of the IETF to actually ratify standards for these algorithms.

**Comment by mwiede** [comment]
OpenEuler https://docs.openeuler.org/en/docs/23.03/docs/ShangMi/overview.html would be an example of a server supporting ShangMi

They even have a docker image one could test against.
