### ISSUE TITLE
com.jcraft.jsch.JSchException: verify: false

### ISSUE THREAD

**Issue by javahokky** [mwiede/jsch#597]
version:
<dependency>
	<groupId>com.github.mwiede</groupId>
	<artifactId>jsch</artifactId>
	<version>0.2.16</version>
</dependency>

when it connects to a exchange by ssh, a error occurs:
com.jcraft.jsch.JSchException: verify: false
	at com.jcraft.jsch.Session.connect(Session.java:347)
	
what's the reason of that error occured and what can i do to resolve the error?

**Comment by norrisjeremy** [comment]
Hi @javahokky,

I would suggest that you more closely review our FAQ, in particular paying close attention to this [question](https://github.com/mwiede/jsch?tab=readme-ov-file#why-do-ssh-rsa-type-keys-not-work-with-this-jsch-fork-and-my-server) as well as this [question](https://github.com/mwiede/jsch?tab=readme-ov-file#is-this-fork-100-compatible-with-original-jsch-because-the-connection-to-my-server-does-not-work-any-more).

Thanks,
Jeremy

**Comment by javahokky** [comment]
已接收

**Comment by javahokky** [comment]
okay, thanks
