### ISSUE TITLE
Reading Identity file from ~/.ssh/config

### ISSUE THREAD

**Issue by ahumaidat** [mwiede/jsch#60]
Does JSCH reads the Identity file used for a certain jump host?

I have the following in my ~/.ssh/config:

```   Host jump     
        ForwardAgent yes    
        HostName $hostName    
        IdentityFile ~/.ssh/$newIdentityFile    
        User $USER    
```
and I get **Auth fail** when connecting to hosts using this jump host.

**Comment by mwiede** [comment]
Hi ahumaidat, is this a question or a bug report?
Please compare to the example given in https://github.com/mwiede/jsch/blob/6feaa590af9a3e0827a219c3be45ac465b90eeba/src/test/java/com/jcraft/jsch/OpenSSHConfigTest.java
It should work.
In your example I am missing the line `Host`, maybe this is causing the issue?

Otherwise, please post the [Logger](https://stackoverflow.com/questions/47411185/jsch-logs-in-files) output, so we might be able to help you further.

**Comment by ahumaidat** [comment]
Using another user fixed the issue.
