### ISSUE TITLE
Query in Release strategy and Support

### ISSUE THREAD

**Issue by ramkumar-92** [mwiede/jsch#637]
Hello,

I am planning to use JSch version 0.2.19 in my application, and I have a couple of questions regarding the release and support strategy:

1. **Release Strategy**:
   - I noticed that new versions are released approximately every two months. Could you please clarify if this is the standard release cadence for JSch? Is there a fixed schedule or criteria for releasing new versions?

2. **Long-Term Support**:
   - What is the long-term support policy for version 0.2.19? Specifically, until when can I expect to receive support, including bug fixes or security updates for this version?
   - If I encounter any bugs or issues in version 0.2.19, how should I report them, and what is the typical response time or process for addressing such issues?

Any insights or additional information regarding the release and support strategy would be greatly appreciated.

Thank you!

**Comment by norrisjeremy** [comment]
Hi @ramkumar-92,

I will let @mwiede clarify his beliefs, especially since he is the founder of this fork & in charge of generating + publishing our releases.

But my opinion is that this is an open source project that @mwiede & myself (as well as any others in the community that would like to help & participate) maintain free of charge, on an ad-hoc basis.
I wouldn't expect there to be any sort of mandatory response times, support policies, etc.

Thanks,
Jeremy

**Comment by ramkumar-92** [comment]
Hi @norrisjeremy ,

Thanks for your prompt response and I understand the process now. 

Thanks,
Ramkumar
