### ISSUE TITLE
JDK11 - Session.connect: java.io.IOException: End of IO Stream Read

### ISSUE THREAD

**Issue by Nuk3R4z0r** [mwiede/jsch#66]
Hi,

Versions tested:
Open/Oracle JDK 11.0.x (any version) <- randomly fails, maybe 1 out of 50
Open/Oracle JDK 1.8.0 181-301 <- works fine

On JDK8, JSCH works perfectly.
When using JDK11, it randomly fails with the following part stacktrace:

Caused by: com.jcraft.jsch.JSchException: Session.connect: java.io.IOException: End of IO Stream Read
        at com.jcraft.jsch.Session.connect(Session.java:568)
        at com.jcraft.jsch.Session.connect(Session.java:186)
        at JschDelegate.connect(JschDelegate.groovy:172)

If you need more info, I will provide it.

**Comment by norrisjeremy** [comment]
Hi @Nuk3R4z0r,

What version of JSch does this occur with?

Thanks,
Jeremy

**Comment by Nuk3R4z0r** [comment]
Hi Jeremy!

Version 1.59

**Comment by norrisjeremy** [comment]
Hi @Nuk3R4z0r,

Can you test with a newer version?
I believe that you may be encountering an issue that was fixed by 2d9681c as part of #15.
The symptoms of this problem would have been identical to what you are: intermittent issues when using Java11+ to connect to an SSH server that supports the `curve25519-sha256` or `curve25519-sha256@libssh.org` Kex algorithms.

Thanks,
Jeremy

**Comment by Nuk3R4z0r** [comment]
Thank you Jeremy, I'll try with a newer version and report back :)

**Comment by Nuk3R4z0r** [comment]
A newer version fixed it, upgraded to .65.
Thanks!
