### ISSUE TITLE
Update "Home page" and "Organization" registration on search.maven.org

### ISSUE THREAD

**Issue by cverges-medallia** [mwiede/jsch#67]
https://search.maven.org/artifact/com.github.mwiede/jsch/0.1.65/jar

Shows the following:
```
Home page	http://www.jcraft.com/jsch/
Organization	JCraft,Inc.
Developers	
Atsuhiko Yamanaka <ymnk at jcraft D0t com>, JCraft,Inc.
```

Since this is a fork, it feels like these values should also be changed so that it's clear to others?

**Comment by norrisjeremy** [comment]
Hi @cverges-medallia,

What a coincidence, I was actually thinking about this earlier today :).

@mwiede, I think we should change this in the pom.xml for the next release, since you and I are the primary caretakers these day, at least with regards to this fork. Do you agree?

Thanks,
Jeremy

**Comment by mwiede** [comment]
Yes I totally agree, we should change it for the next release.

When starting the fork, I thought that we get contact to jcraft or Atsuhiko
Yamanaka so that we can merge all changes upstream but unfortunately I
never got an answer. Maybe something happened to him, I can't believe he
just disappeares.

Cheers,
Matthias


Jeremy Norris ***@***.***> schrieb am Do., 2. Sep. 2021,
20:34:
