### ISSUE TITLE
Incompatibility with legacy jsch as used by jgit

### ISSUE THREAD

**Issue by ST-DDT** [mwiede/jsch#85]
I tried to replace the original jsch with this updated variant, but that caused an NPE.

````java
CloneCommand cloneCommand = Git.cloneRepository()
                .setURI("git@github.com:mwiede/jsch.git")
                .setDirectory(new File("target/junit/clone-test));
assertDoesNotThrow(cloneCommand::call).close(); // <-- Error
````

This is caused by the following line: [Source](https://gerrit.googlesource.com/jgit/+/refs/tags/v5.13.0.202109080827-r/org.eclipse.jgit.ssh.jsch/src/org/eclipse/jgit/transport/JschConfigSessionFactory.java#401)

````java
JSch.setConfig("ssh-rsa", JSch.getConfig("signature.rsa"));
JSch.setConfig("ssh-dss", JSch.getConfig("signature.dss"));
````

In the original jsch version this was set to:

````java
config.put("signature.rsa", "com.jcraft.jsch.jce.SignatureRSA");
````

This version no longer sets these properties.

My dependencies:

````xml
        <!-- Git -->
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
            <version>5.13.0.202109080827-r</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit.ssh.jsch</artifactId>
            <version>5.13.0.202109080827-r</version>
            <exclusions>
                <exclusion>
                    <groupId>com.jcraft</groupId>
                    <artifactId>jsch</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.mwiede</groupId>
            <artifactId>jsch</artifactId>
            <version>0.1.68</version>
        </dependency>
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch.agentproxy.connector-factory</artifactId>
            <version>0.0.9</version>
        </dependency>
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch.agentproxy.jsch</artifactId>
            <version>0.0.9</version>
            <exclusions>
                <exclusion>
                    <groupId>com.jcraft</groupId>
                    <artifactId>jsch</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
````

Stacktrace

````txt
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:mwiede/jsch.git: remote hung up unexpectedly
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:224)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:303)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:178)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:72)
	... 71 more
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:mwiede/jsch.git: remote hung up unexpectedly
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:313)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:142)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:94)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1309)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:213)
	... 74 more
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at com.jcraft.jsch.JSch.setConfig(JSch.java:666)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createDefaultJSch(JschConfigSessionFactory.java:401)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getJSch(JschConfigSessionFactory.java:361)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:317)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:184)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:108)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
	... 79 more
````

**Comment by norrisjeremy** [comment]
Hi @ST-DDT,

1. The original `signature.rsa` config item was removed as part of adding support for `rsa-sha2-256` & `rsa-sha2-512`.
2. This JSch fork already contains a config item for `ssh-rsa`: overriding it is not necessary, and could possibly lead to issues.

The quickest way for them to fix it would probably be to simply check whether the config items they attempt to add are already present or not:
```
if (JSch.getConfig("ssh-rsa") == null) {
  JSch.setConfig("ssh-rsa", JSch.getConfig("signature.rsa"));
}
if (JSch.getConfig("ssh-dss") == null) {
  JSch.setConfig("ssh-dss", JSch.getConfig("signature.dss"));
}
```

Also, I'm not sure if they would be interested in changing their JSch dependency long-term to this particular fork, since the original JSch from JCraft is unmaintained these days? I'd be happy (and I'm sure @mwiede would be as well) to collaborate with them on any changes we could make in this fork that could improve their integration with JSch: I suspect this code was added by them to workaround a deficiency in the original JSch.

Thanks,
Jeremy

**Comment by ST-DDT** [comment]
I tested with the libraries as used in the commit, but I was unable to make it work with windows 10 and java 11 64bit.
Is it possible that the used libraries only support it for unix systems || Java 16+?
I updated my glue code a bit to account for that one missing method and now it also works on windows (with jsch.agentporxy.jsch).

The problem might be the use of `Paths.get(...)` as that converts the unix paths to windows paths, which might cause the agent/socket to fail to connect.

**Comment by norrisjeremy** [comment]
Hi @ST-DDT,

I've only tested on Linux & macOS, so I'm not sure if there could be issues on Windows.

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
> > Hi @ST-DDT,
> > Am I correct in my understanding that after the changes you submitted with #86 everything worked for you on Windows?
> > Thanks, Jeremy
> 
> Yes, it does. After the PR is merged I will build the project locally and test again. Then I will probably propose a convenience method to `AgentIdentityRepository` that automatically tries to select the correct connector. (Along with some javadocs that explain which dependencies to include)

Hi @ST-DDT ,

That is excellent to hear!
Am I correct in understanding that the convenience method you are referring to would be some sort of auto-selection of the connector based upon the OS?
If so, I had considered that but elected not to because I thought both connectors ought to be usable on Windows.
It's my understanding that recent versions of Windows support unix domain sockets, so I believe it should be possible for Windows users to utilize either the PageantConnector or SSHAgentConnector, therefore I didn't want to lock users into one or the other connector implementations.
I don't know if you would be in a position to confirm if this is true or not?

Thanks,
Jeremy

**Comment by mwiede** [comment]
closing this as it is solved. Somebody asked on Stackoverflow compare at https://stackoverflow.com/questions/73046450/spring-cloud-config-server-algorithm-negotiation-fail-problem
